name: Test, Build and Push PushGateway-Cleaner Image
on: [push, pull_request]

jobs:
  test:
    name: Intgration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Run Tests (Mocha)
        run: npm test
        env:
          PUSHGATEWAY_URL: http://localhost:9091


  build-and-push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Read package.json
        uses: pushgateway-cleaner/read-package-version-actions@v1
        id: package-version
      - name: Show version number
        run: echo "Version is ${{ steps.package-version.outputs.version }}"
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: zooz/pushgateway-cleaner
          push: true
          tags: latest